### ISSUE TITLE
Task: Copy vendors from previous release

### ISSUE THREAD

**Issue by ramunasd** [andres-montanez/Magallanes#156]
This would speed up composer actions for new release.

**Comment by eps90** [comment]
I think CLI is a bad idea here because of CI and CD tools. They cannot wait for any user input during the build. But there may be some workaourd by using `--non-interactive`/`-in` option and prevent interactive mode.
To complete @jhuet comment: After you've got shared `vendor` directory, you can run composer install after your symlink has been made. Then:
* if there are no updates in `composer.lock` it'll pass on and continue deployment without changing your `vendor`'s contents
* otherwise it will install only new dependencies (or upgrades)
