### ISSUE TITLE
Built-in release task fails on chown

### ISSUE THREAD

**Issue by miraage** [andres-montanez/Magallanes#222]
`chown` command is only can be executed if you are `root` user.
I want to deploy as `deploy` user, so task fails.

How do I figure out this problem?

https://github.com/andres-montanez/Magallanes/blob/a0f49203338770d971f82f204129d025c72c4eaf/Mage/Task/BuiltIn/Deployment/ReleaseTask.php#L77

Should look like

``` php
            if ($resultFetch && $userGroup != '') {
                $command = 'sudo chown -R ' . $userGroup . ' ' . $currentCopy
                    . ' && '
                    . 'sudo chown ' . $userGroup . ' ' . $releasesDirectory;
                $result = $this->runCommandRemote($command);
                if (!$result) {
                    return $result;
                }
            }
```

(also 1 more occurence of `chown` in this task)

**Comment by eps90** [comment]
@miraage I think it isn't the best idea for projects where deploy user has no `sudo` permissions. This could be done by giving `use_sudo` option in configuration like Capistrano does. I think there's a need to look deeper into deployment process to minimize the need of calling `chown` command.

**Comment by miraage** [comment]
My user has `sudo` pemissions, but `chown` command **requires** `sudo` prefix when you aren't `root`.

**Comment by eps90** [comment]
Of course - but I am saying about optional `use_sudo` configuration variable. Usage would look like:
```php
            $sudo = $config->get('use_sudo', false) ? 'sudo' : '';
            if ($resultFetch && $userGroup != '') {
                $command = "$sudo chown -R " . $userGroup . ' ' . $currentCopy
                    . ' && '
                    . "$sudo chown " . $userGroup . ' ' . $releasesDirectory;
                $result = $this->runCommandRemote($command);
                if (!$result) {
                    return $result;
                }
            }
```
I would not hard code it because users who deploy with non-sudo user will get errors instantly. So the best way is to allow developer to choose this level.
In the other hand - as you say - `chown` will never run if command is called without `sudo`. I'll take a look, it looks like something urgent.

**Comment by eps90** [comment]
Related to #111 and #226

**Comment by drAlberT** [comment]
BTW, I set **FS ACL** on my sites root so I don't need to run `chown` .. but magallanes do it under the curtains and fails :(

I propose to make the `chown` run optional too ..

**Comment by danakil** [comment]
Hi ! My shell user is not root. I created it with ISPConfig and it is associated to my website so the right group/owner is already set on all uploaded files for a release. For now, the release process fails because I'm not allowed to execute chown and, if I understand well, I don't even need to chown my files.
Like drAlberT said, chown should be made optionnal.

**Comment by drAlberT** [comment]
@danakil see my fork .. it should allow it

**Comment by danakil** [comment]
@drAlberT Cool, it works, thank you !
For information to all the interested people, I had to add a   
owner: "user:group"
line in the "deployment" section of the config file.

I hope your fork or a similar feature would be merged in the main branch.

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks to all!
