### ISSUE TITLE
define a precise CS checkable with php-cs-fixer

### ISSUE THREAD

**Issue by drAlberT** [andres-montanez/Magallanes#241]
IT would be simpler to be able to automatically run CS test on a well defined basis ..

If I am missing something please point me to the doc for configure an automated test for CS, I'd like to have a .php_cs file in the project or its counterpart if a CS fixer is already being used

thanks in advance

**Comment by drAlberT** [comment]
OK I found the doc: --level=psr2

I'll provide a PR for including a well configured .php_cs file

**Comment by eps90** [comment]
Yes, there is an option to connect `phpcs` with TravisCI and there are plenty more services that we could use to provide code style analysis during CI build. I've already thought about it and there are some disadvantages or problems that I've met so far and I didn't resolve them or I didn't search to find the answer :)
* Analyze only the pushed code - I'm not sure that pure `phpcs` can do it.
* To provide more reliable code analysis we should also integrate `phpmd`, `pdepend`, tools for detecting "copy-pastes" and duplicates. (This is the way I have done on my private servers but I use SonarQube for static code analysis)
* The build process can last very long

I mentioned about code style in `contributing` document and I refer to the rules I know during the code review but one's brain can be tricky and can miss some violations during the CR. One of the alternatives is to add a git hook on your local machine to run code analysis before push **only** with the code diff. That's cool but we won't avoid the mess because **everyone** should configure it and I belive it's unpossible.

**Comment by drAlberT** [comment]
@eps90 I'm talking about a simpler issue .. just include a php-cs-fix configuration file intended to enable the coder to simply run php-cs-fix (or, better, "composer cs-fix") on demand .. no hooks, not automagic

I think all the mage tree should be already be fixed, so simply running `php-cs-fix fix` (not only on the pushed code) should be good too ..

I'm pushing such a file on my fork, going to test and fine tune (I'll add php-cs-fix in require-dev too)

PS:
OT, why require a specific release of phpunit? should suffice something like ">=4.2" .. or not?

**Comment by eps90** [comment]
@drAlberT Ahh, ok, now I see what you've meant ;) Yes, it would be great to include coding standards configuration in the repo.
And yes, you're right - PHPUnit version should be at least with tilde before version number.

**Comment by drAlberT** [comment]
Iìll provide a PR shortly

**Comment by drAlberT** [comment]
#244

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, so no further changes will be integrated to it, focus is for the next next mayor version.
Many thanks to all!
