### ISSUE TITLE
Deployment best practices

### ISSUE THREAD

**Issue by mbaeuerle** [andres-montanez/Magallanes#328]
I wanted to use Magallanes for deploying a Laravel application (using v.3.0 dev-master). But I am not sure what the best workflow is. 
When I want to deploy the master branch, my whole local directory is copied to the server, including my dev `.env` and vim `.swp` files.
So what is the best practice in this case? Should I create a local deployment directory where I don't develop but just run the deployment on and Magallanes fetches the latest code via git?
Thanks for your advice. Maybe it is written in the docs, but I could not find it. If it's not there maybe it is worth mentioning there in a "getting started" chapter, so it is easier to get things started quickly.

**Comment by aschempp** [comment]
I’m not familiar with v3 yet, but you can exclude files from being deployed. So it should be fairly easy not to upload the .env files or similar stuff.

We’re using Mage in a Symfony environment, and we’re not deploying the parameters.yml and also run composer install on the remote servers by default.

**Comment by andres-montanez** [comment]
Hi! Thank you both for taking interest in this project!
@mbaeuerle regarding your question, as @aschempp mentioned you can exclude files and directories.
I'm not familiar with Laravel but in my case for Symfony I exclude the var/log and var/cache directories.
Also I may exclude the vendors and run the composer/install command on the remote host (at the on-deploy stage).

In your case you could exclude those files. Magallanes will copy everything if not specified otherwise.

I like the idea of having a section in the docs for a quick Getting Started and also a Best Practices!

**Comment by mbaeuerle** [comment]
Ok thanks for your fast replies! I will try the exclude file approach and the approach with creating a blank deployment directory and see what fits best in my case. 
I close the issue for now.
