### ISSUE TITLE
Commit the composer.lock

### ISSUE THREAD

**Issue by Toflar** [andres-montanez/Magallanes#331]
As this is a project, you should commit the `composer.lock` file. Cheers :)

**Comment by andres-montanez** [comment]
Hi @Toflar , I had a bit of a debate with myself about this, I added it, then remove it, then added it and remove it again.

I decided to keep it of the repo mainly because Magallanes is more close to a library than to an app (and the Composer documentation is indifferent regarding the lock in this case), and also without it we can ensure that the CI tests will run with the latests versions of the dependencies.

With the lock added the tests will run with those versions, but when Magallanes is used as a dependency those versions wont be taken into consideration, so in short we may end up running CI tests with outdated versions compared to the average user.

**Comment by Toflar** [comment]
True, I agree with you. I use it as a dependency too, it's all good :) It's good the issue is here anyway, for future reference when other people think the same ;) Closing, thanks for taking the time!
