### ISSUE TITLE
Common configuration for environments?

### ISSUE THREAD

**Issue by Thomas-Pamono** [andres-montanez/Magallanes#363]
Hello,

I have multiple testing environments which essentially only differ in the host_path.
It would be really helpful to have a kind of global environment configuration with a kind of inheritance to not repeat it over and over again with the same settings and tasks.

**Comment by dn5** [comment]
Interesting, got the same idea several times through using Mage. Since you are talking about `host_path` means you are asking for Mage v3 implementation. I think thats fairly easy to implement since the YAML is in any case manipulated through array so such would just demand on appending `common` beforehand.

**Comment by andres-montanez** [comment]
Hi, thanks for your feedback.
I want to avoid a "global config", but I could work with the idea of "aliasing" an environment.
Still this is not on the roadmap right now, but I will put it on the nice to have list.

Regards!
