### ISSUE TITLE
custom current symlink

### ISSUE THREAD

**Issue by matiux** [andres-montanez/Magallanes#387]
HI,
I need to custom current symlink. I would like to choice link name by config file.
It would be great if also releases directory could be chosen

thanks

**Comment by duraki** [comment]
That was requested by me @ #371 and the response was rather interesting. The developer, in this case respected Andres Monranez, with all due fine efforts spent on this project (I use Mage v1 & v3 for all my presalt+devops "deploy" tasks) said that such a feature is (rather, ironic) a "cosmetic feature" and this would "break" code "quality" and "stability".
  
Such would require creating him additional unit tests plus parsing through configuration. Although unit tests are boring to develop (we all know that pain), one of the main feature of `symlink` from v1 was not backward compatible. Which is also interesting, since all the details are loaded at entry point and reuse is fairly easy if possible. An integration wouldn't cost much but would definitely help with locating same settings as in v1.

Not to speak much, I've been developing Mage v1/v2 features @ work since we use it and I have it in the Phab repo. I'll try to commit a patch to this is issue or mine through next week (traveling), which was not covered in ut, but I hope one day I will.

I also having a separate branch that does parallel deploy which is requested @ #349. Super easy to make using `pssh` and `prsync` which are Python scrips and can be ran everywhere I got around 30% less waiting which is great imo.
  
Wondering just, do you want patches, or a fork on my account? Our version haven't been merged from origin master to current local so we missed various things but everything is replaceable.

**Comment by duraki** [comment]
Long delay, had a lot of things on my hand, here is a hotfix patch:

```diff
diff --git a/src/Task/BuiltIn/Deploy/ReleaseTask.php b/src/Task/BuiltIn/Deploy/ReleaseTask.php
index e78eebe..ad0dd00 100644
--- a/src/Task/BuiltIn/Deploy/ReleaseTask.php
+++ b/src/Task/BuiltIn/Deploy/ReleaseTask.php
@@ -40,9 +40,8 @@ class ReleaseTask extends AbstractTask implements ExecuteOnRollbackInterface

         $hostPath = rtrim($this->runtime->getEnvOption('host_path'), '/');
         $releaseId = $this->runtime->getReleaseId();
-        $symlink = $this->runtime->getEnvOption('symlink');

-        $cmdLinkRelease = sprintf('cd %s && ln -snf releases/%s %s', $hostPath, $releaseId, $symlink);
+        $cmdLinkRelease = sprintf('cd %s && ln -snf releases/%s current', $hostPath, $releaseId);

         /** @var Process $process */
         $process = $this->runtime->runRemoteCommand($cmdLinkRelease, false);
```
  
To use, set a `symlink` inside your `.mage.yml` configuration for specific environment.

**Comment by andres-montanez** [comment]
Hi, LTDR. Bottom line, you can easily workaround this with your virtual hosts configuration.
And is easier for me to maintain the code if I have less variables, specially as I stated earlier, this is not a deal breaker and you can configure your virtual host in any way you want.

Regards.
