### ISSUE TITLE
Releases on Rsync

### ISSUE THREAD

**Issue by duraki** [andres-montanez/Magallanes#391]
In Mage v1, there was ability to use `Releases` with Rsync strategy. Lately, with Mage v3, I've been using `Tar` strategy which allows `Releases`, although while experimenting new features with Rsync, this option throws an exception.

Is there a reason why Mage v3 stopped supporting this feature when using `Rsync` as a method of deployment?

**Comment by andres-montanez** [comment]
Hi, rsync is used when you do not use releases, because you are essentially pushing only new changes. And tar is used when you use releases because you need to copy a full set of your application, and copying a tar is far more efficient and easy to track, rsyncing to an empty directory doesn't make much sense.

Regards!

**Comment by duraki** [comment]
Thank you for a clear response. That makes sense.
