### ISSUE TITLE
Custom global tasks

### ISSUE THREAD

**Issue by JoeSimsen** [andres-montanez/Magallanes#51]
Hey there,

What (if any) is the policy about creating custom tasks, for multiple projects? These can not be placed with the project, it would be better to place them in the Magallanes folder.

This works if I create a custom folder in BuiltIn and put them there. However, that is not preferable when working with version control, ie git. 

Can you add a default folder next to BuiltIn, maybe called Global, whose contents have a git ignore? Or does anyone have a better idea?

I would like to hear your thoughts!

**Comment by chrisfromredfin** [comment]
I'm not sure why this issue is closed. I think the OP wanted (as I do! :) ) the ability to create a custom Task that can be shared amongst all my mage projects.

I have a number of sites that I will be deploying with magallanes but they're all Drupal - so I want to add some commands to clear Drupal caches - but I don't want to add the same custom command to every .mage/tasks, since I'll have a massive redundancy of code. 

Or, am I missing something here and I should be using custom commands in some way to provide "global custom tasks?"

**Comment by andres-montanez** [comment]
Hi @chrisfromredfin the feature is available :)
I don't recall if it is already on version 1.0.3, but certainly it is on master.

**Comment by chrisfromredfin** [comment]
It is available how - as you mentioned: "define a parameter in each general.yml config, to point to a directory which will contain global tasks." I'm also seeing things about being able to load from a different namespace or something, so is it available that way then instead?

The documentation still says "Every custom task must be stored in your .mage/tasks directory."

So just having trouble finding where it's implemented, even wading through source code and git diff's (I probably would benefit from a better grasp of PSR-4 and autoloading, etc).

**Comment by andres-montanez** [comment]
Point taken. Yes, the "global" is not implemented.
Lets reopen to implement the feature :)

**Comment by chrisfromredfin** [comment]
It looks like there is work being done here that is pretty current:
https://github.com/andres-montanez/Magallanes/pull/189

It references issue #188 as the itch being scratched.

**Comment by eps90** [comment]
yes, @chrisfromredfin we're discussing about it :) If you have something to share with us, go on :) Every idea is valueable for the project!

**Comment by jhuet** [comment]
I'm using a workaround on that matter by creating a ``.mage`` directory related to no project. So i basically only have .mage and vendor folders there. Then i have all my custom shared tasks here. So for any deployment i go in that directory and deploy the project i want. Of course that means that you also need to have all the configurations of all your websites in here and not in each project directory.

**Comment by chrisfromredfin** [comment]
@jhuet Meaning you just define multiple environments, so instead of staging.yml and production.yml, you have things like staging-abc.yml, staging-def.yml, production-abc.yml, production-def.yml, etc?

**Comment by jhuet** [comment]
@chrisfromredfin yes exactly.

**Comment by chrisfromredfin** [comment]
@jhuet using this workaround, are you finding yourself "in the wrong folder" for your tasks then? For example, I am not allowing a deployment (via rsync) to production except from the 'master' branch - so I've got a Task VerifyBranch. However, running my mage deploy from my outside-of-environment folder, the git command fails because I'm not in a repo (eventually I will be in a repo, so even battier). 

Do you just...

    $stash = getcwd(); 
    cwd($pathFromEnvironmentConfig); 
    // ...do stuff...
    cwd($stash); 

...inside your task, or is there a more Magallanes-y approach to this? (Or do you not have this issue :) )

**Comment by jhuet** [comment]
@chrisfromredfin, absolutely, that's why i had to create (this PR)[https://github.com/andres-montanez/Magallanes/pull/171/files] for ``Scm/ChangeBranchTask`` where you should find tips on how to modify the tasks that are giving you a hard time right now.

Basically, every task that requires to do stuff in the actual repo should always ``cd`` into it beforehand. As most people uses Mage from their repo it's true that this problem hasn't been spotted everywhere.

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, this feature will be available in the next mayor version. You will be able to pull Tasks from anywhere your Composer Autoload has access to.
Many thanks to all!

**Comment by jhuet** [comment]
Glad to see things moving forward! Welcome back @andres-montanez :)

**Comment by andres-montanez** [comment]
Thank you! :D
